import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getAllTodos } from '../lib/posts';
import Card from '../components/Card';

export default function Home({ allTodos }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Completed</h2>
        {allTodos.filter((item) => item.completed).map(({ id, title, completed }) => (
          <Card key={id} title={title} completed={completed} />
        ))}
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const allTodos = await getAllTodos();
  return {
    props: {
      allTodos,
    },
  };
}
