import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getAllTodos } from '../lib/posts';

export default function Home({ allTodos }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {allTodos.map(({ id, title }) => (
          <li key={id}>
            {title}
          </li>
        ))}
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const allTodos = await getAllTodos();
  return {
    props: {
      allTodos,
    },
  };
}
